import { QueryClient } from "@tanstack/react-query";
import { EPresetTimes } from "./types";

export const itemsPerPage = 50;

export const StatusName = [
  { name: "Активный", id: 1 },
  { name: "Не активный", id: 0 },
];
export const priceNum = (val: number) => {
  return val
    ?.toFixed(2)
    ?.toString()
    ?.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};

// export const fixedString = (value: string) => {
//   return value
//     .split("")
//     .filter((item) => {
//       return [" ", "-", "(", ")"].indexOf(item) === -1;
//     })
//     .join("");
// };

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      cacheTime: EPresetTimes.MINUTE * 5,
      staleTime: EPresetTimes.MINUTE * 5,
    },
  },
});

export const isMobile = window.innerWidth <= 1200;

export const imageConverter = (img: File) => {
  if (img?.size) return URL.createObjectURL(img);
  return "";
};

export const PaymentTypes = [
  { id: 0, name: "Наличные" },
  { id: 1, name: "На карту" },
];
export const mockOrder = {
  items: [
    {
      id: 1,
      title: "Macbook",
      price: "120.55500",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 1,
      payer_id: 1,
      files: [
        "files/mH8IY5NRlNPPbx2fROQo9z3Q9SkTIS2023-09-27 10.10.03.jpg",
        "files/TPsYsOlbhoYP46N4UUTZvjUCJK6USA2023-08-05 15.07.14.jpg",
      ],
      status: 0,
      order_sp: {
        name: "fabrica",
        status: 1,
        id: 1,
        sphereuser: [
          {
            id: 1,
            sphere_id: 1,
            status: 1,
            sequence: 1,
            user_id: 2,
            sp_user: {
              username: "kimsan",
              status: 1,
              created_at: "2023-11-17T10:36:02.064546+05:00",
              full_name: "string",
              is_client: null,
              id: 2,
              role_id: null,
              phone_number: "998991176823",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
          {
            id: 3,
            sphere_id: 1,
            status: 1,
            sequence: 2,
            user_id: 3,
            sp_user: {
              username: "test",
              status: 1,
              created_at: "2023-11-17T10:36:11.804171+05:00",
              full_name: "Gayratbek",
              is_client: null,
              id: 3,
              role_id: null,
              phone_number: "998991176825",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
          {
            id: 6,
            sphere_id: 1,
            status: 1,
            sequence: 4,
            user_id: 10,
            sp_user: {
              username: "testLogin",
              status: 1,
              created_at: "2023-11-20T10:12:38.584420+05:00",
              full_name: "Nurmuhammad",
              is_client: null,
              id: 10,
              role_id: 1,
              phone_number: "998909090909",
              user_role: {
                id: 1,
                name: "Admin ",
              },
              tg_id: null,
            },
            name: null,
          },
          {
            id: 7,
            sphere_id: 1,
            status: 0,
            sequence: 4,
            user_id: 10,
            sp_user: {
              username: "testLogin",
              status: 1,
              created_at: "2023-11-20T10:12:38.584420+05:00",
              full_name: "Nurmuhammad",
              is_client: null,
              id: 10,
              role_id: 1,
              phone_number: "998909090909",
              user_role: {
                id: 1,
                name: "Admin ",
              },
              tg_id: null,
            },
            name: null,
          },
          {
            id: 5,
            sphere_id: 1,
            status: 1,
            sequence: 3,
            user_id: 9,
            sp_user: {
              username: "develop",
              status: 2,
              created_at: "2023-11-20T09:28:18.650728+05:00",
              full_name: "Muhammad",
              is_client: null,
              id: 9,
              role_id: null,
              phone_number: "998909520009",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-17T11:00:16.812724+05:00",
      order_hi: [
        {
          id: 1,
          user_id: 2,
          order_id: 1,
          status: 0,
          comment: null,
          created_at: "2023-11-17T11:00:16.828054+05:00",
        },
      ],
      purchaser: null,
      is_urgent: null,
      comment: null,
    },
    {
      id: 2,
      title: "Macbook",
      price: "119.55500",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 1,
      payer_id: 1,
      files: [
        "files/mH8IY5NRlNPPbx2fROQo9z3Q9SkTIS2023-09-27 10.10.03.jpg",
        "files/TPsYsOlbhoYP46N4UUTZvjUCJK6USA2023-08-05 15.07.14.jpg",
      ],
      status: 0,
      order_sp: {
        name: "fabrica",
        status: 1,
        id: 1,
        sphereuser: [
          {
            id: 1,
            sphere_id: 1,
            status: 1,
            sequence: 1,
            user_id: 2,
            sp_user: {
              username: "kimsan",
              status: 1,
              created_at: "2023-11-17T10:36:02.064546+05:00",
              full_name: "string",
              is_client: null,
              id: 2,
              role_id: null,
              phone_number: "998991176823",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
          {
            id: 3,
            sphere_id: 1,
            status: 1,
            sequence: 2,
            user_id: 3,
            sp_user: {
              username: "test",
              status: 1,
              created_at: "2023-11-17T10:36:11.804171+05:00",
              full_name: "Gayratbek",
              is_client: null,
              id: 3,
              role_id: null,
              phone_number: "998991176825",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
          {
            id: 6,
            sphere_id: 1,
            status: 1,
            sequence: 4,
            user_id: 10,
            sp_user: {
              username: "testLogin",
              status: 1,
              created_at: "2023-11-20T10:12:38.584420+05:00",
              full_name: "Nurmuhammad",
              is_client: null,
              id: 10,
              role_id: 1,
              phone_number: "998909090909",
              user_role: {
                id: 1,
                name: "Admin ",
              },
              tg_id: null,
            },
            name: null,
          },
          {
            id: 7,
            sphere_id: 1,
            status: 0,
            sequence: 4,
            user_id: 10,
            sp_user: {
              username: "testLogin",
              status: 1,
              created_at: "2023-11-20T10:12:38.584420+05:00",
              full_name: "Nurmuhammad",
              is_client: null,
              id: 10,
              role_id: 1,
              phone_number: "998909090909",
              user_role: {
                id: 1,
                name: "Admin ",
              },
              tg_id: null,
            },
            name: null,
          },
          {
            id: 5,
            sphere_id: 1,
            status: 1,
            sequence: 3,
            user_id: 9,
            sp_user: {
              username: "develop",
              status: 2,
              created_at: "2023-11-20T09:28:18.650728+05:00",
              full_name: "Muhammad",
              is_client: null,
              id: 9,
              role_id: null,
              phone_number: "998909520009",
              user_role: null,
              tg_id: null,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-17T11:19:49.363911+05:00",
      order_hi: [
        {
          id: 2,
          user_id: 2,
          order_id: 2,
          status: 0,
          comment: null,
          created_at: "2023-11-17T11:19:49.375093+05:00",
        },
      ],
      purchaser: null,
      is_urgent: null,
      comment: null,
    },
    {
      id: 3,
      title: "macbook",
      price: "1300.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: ["files/sDZdBumrHp8oGpGLRvDZnVE0e9cmUC2023-08-03 12.40.41.jpg"],
      status: 0,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-20T12:11:05.101717+05:00",
      order_hi: [
        {
          id: 3,
          user_id: 11,
          order_id: 3,
          status: 0,
          comment: null,
          created_at: "2023-11-20T12:11:05.121166+05:00",
        },
      ],
      purchaser: "nicaragua",
      is_urgent: 1,
      comment: "Hello world",
    },
    {
      id: 5,
      title: "macbook",
      price: "1200.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: ["files/sDZdBumrHp8oGpGLRvDZnVE0e9cmUC2023-08-03 12.40.41.jpg"],
      status: 1,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-20T12:15:24.095645+05:00",
      order_hi: [
        {
          id: 5,
          user_id: 11,
          order_id: 5,
          status: 1,
          comment: null,
          created_at: "2023-11-20T12:15:24.114100+05:00",
        },
      ],
      purchaser: "nicaragua",
      is_urgent: 1,
      comment: "Hello world",
    },
    {
      id: 4,
      title: "macbook",
      price: "1200.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: ["files/sDZdBumrHp8oGpGLRvDZnVE0e9cmUC2023-08-03 12.40.41.jpg"],
      status: 1,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-20T12:12:12.051296+05:00",
      order_hi: [
        {
          id: 4,
          user_id: 11,
          order_id: 4,
          status: 1,
          comment: null,
          created_at: "2023-11-20T12:12:12.058292+05:00",
        },
      ],
      purchaser: "nicaragua",
      is_urgent: 1,
      comment: "Hello world",
    },
    {
      id: 8,
      title: "macbook",
      price: "1200.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: null,
      status: 1,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-21T11:54:49.462099+05:00",
      order_hi: [
        {
          id: 6,
          user_id: 11,
          order_id: 8,
          status: 1,
          comment: null,
          created_at: "2023-11-21T11:54:49.485279+05:00",
        },
      ],
      purchaser: "hell oworld",
      is_urgent: 1,
      comment: "faster please",
    },
    {
      id: 9,
      title: "macbook",
      price: "100.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: null,
      status: 1,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-21T12:02:50.769651+05:00",
      order_hi: [
        {
          id: 7,
          user_id: 11,
          order_id: 9,
          status: 1,
          comment: null,
          created_at: "2023-11-21T12:02:50.783345+05:00",
        },
      ],
      purchaser: "hell oworld",
      is_urgent: 1,
      comment: "faster please",
    },
    {
      id: 10,
      title: "macbook",
      price: "1200.00000",
      payment_type: 1,
      supplier: "macbro",
      sphere_id: 4,
      payer_id: 1,
      files: null,
      status: 1,
      order_sp: {
        name: "odam qoshilmasin",
        status: 1,
        id: 4,
        sphereuser: [
          {
            id: 4,
            sphere_id: 4,
            status: 1,
            sequence: 1,
            user_id: 11,
            sp_user: {
              username: "gayrat6ek",
              status: 1,
              created_at: "2023-11-20T12:01:24.769639+05:00",
              full_name: null,
              is_client: null,
              id: 11,
              role_id: null,
              phone_number: "998991176723",
              user_role: null,
              tg_id: 1285975410,
            },
            name: null,
          },
        ],
      },
      order_py: {
        id: 1,
        name: "Nortron trade ",
        status: 1,
      },
      created_at: "2023-11-21T12:09:42.064882+05:00",
      order_hi: [
        {
          id: 8,
          user_id: 11,
          order_id: 10,
          status: 1,
          comment: null,
          created_at: "2023-11-21T12:09:42.068488+05:00",
        },
      ],
      purchaser: "hell oworld",
      is_urgent: 1,
      comment: "faster please",
    },
  ],
  total: 8,
  page: 1,
  size: 50,
  pages: 1,
};
